const SYSTEM_CODE="SHAROUSHI";
const VERSION="DPRO-CONTROL-ADAPTER-1.0-SHAROUSHI-20260823-R2V2";
const CORE="https://ropwvdnohadwxfbkcopx.supabase.co/functions/v1/dpro-sharoushi-control-adapter";
const SAFE_DEMO="https://ropwvdnohadwxfbkcopx.supabase.co/functions/v1/dpro-sharoushi-safe-demo";
const LEGACY="https://dpro-consult-line-api.dpromstk2000.workers.dev";
const DB_VERSION="SHAROUSHI-DB-PR2-20260823";
const FRONTEND_VERSION="SHAROUSHI-PR2-FRONTEND-20260823";
const LEGACY_VERSION="CONSULT-9-R1-STAFF-ID-UUID-FIX-20260714";
const ALLOWED=["https://dpromstk2000-lab.github.io"];
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
function origin(req:Request){return req.headers.get("Origin")||""}
function okOrigin(req:Request){const o=origin(req);return !o||ALLOWED.includes(o)}
function headers(req:Request){const o=origin(req),h=new Headers({"Vary":"Origin","Access-Control-Allow-Methods":"GET,POST,PATCH,PUT,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization,X-Admin-Code,X-DPRO-Demo,X-Staff-Session,X-Line-ID-Token,X-Requested-With","Access-Control-Max-Age":"86400","Cache-Control":"no-store","Content-Type":"application/json; charset=utf-8","X-DPRO-System":SYSTEM_CODE,"X-DPRO-Adapter-Version":VERSION});if(ALLOWED.includes(o))h.set("Access-Control-Allow-Origin",o);return h}
function json(req:Request,b:any,s=200){return new Response(JSON.stringify(b,null,2),{status:s,headers:headers(req)})}
function fail(req:Request,c:string,m:string,s=400){return json(req,{ok:false,code:c,error:m},s)}
async function getj(url:string,init:RequestInit={}){const r=await fetch(url,{...init,cache:"no-store"}),t=await r.text();let d:any;try{d=t?JSON.parse(t):null}catch{d={raw:t}}return{status:r.status,data:d,headers:r.headers}}
async function db(){if(!SUPABASE_URL||!SERVICE)return{ok:false};const r=await getj(`${SUPABASE_URL}/rest/v1/sharoushi_system_versions?singleton=eq.true&select=database_version,frontend_version,adapter_version,worker_version,environment,updated_at&limit=1`,{headers:{apikey:SERVICE,Authorization:`Bearer ${SERVICE}`}});const row=Array.isArray(r.data)?r.data[0]:null;return{ok:r.status===200&&!!row,...row}}
async function front(){const r=await fetch(`${SAFE_DEMO}/runtime-contract.js?v=${Date.now()}`,{cache:"no-store"}).catch(()=>null);if(!r)return{ok:false,status:0,version:null};const t=await r.text(),m=t.match(/SHAROUSHI_FRONTEND_VERSION\s*=\s*["']([^"']+)["']/);return{ok:r.ok&&m?.[1]===FRONTEND_VERSION,status:r.status,version:m?.[1]||null}}
async function legacy(){const r=await getj(`${LEGACY}/api/health`);return{ok:r.status===200&&r.data?.ok===true,status:r.status,version:r.data?.version||null,database:r.data?.database||null,productionGuard:r.data?.production_guard===true}}
async function health(req:Request){const[d,f,l]=await Promise.all([db(),front(),legacy()]);const aligned=d.ok&&f.ok&&l.ok&&d.database_version===DB_VERSION&&d.frontend_version===FRONTEND_VERSION&&d.adapter_version===VERSION&&d.worker_version===VERSION&&l.version===LEGACY_VERSION;return json(req,{ok:d.ok&&l.ok,service:"DPRO SHAROUSHI Safe Control Gateway",systemCode:SYSTEM_CODE,officeCode:"dpro_consult_demo",environment:d.environment||"precontract_demo",version:VERSION,workerVersion:VERSION,adapterVersion:VERSION,databaseVersion:d.database_version||null,frontendVersion:f.version,database:{ok:d.ok,office_code:"dpro_consult_demo",office_name:l.database?.office_name||"DPRO社会保険労務士事務所",version:d.database_version||null},productionGuard:true,production_guard:true,demoGuard:true,dbOk:d.ok,cors:{allowlist:ALLOWED,wildcard:false},lineIdentityMode:"deferred_until_contract_fail_closed",staffAuthority:"server_session_permission_revoke_audit",slotMinutes:30,pastDateServerGuard:true,calendarExceptionAuthority:true,coreAdapterVersion:"DPRO-CONTROL-ADAPTER-1.0-SHAROUSHI-20260823-R2",legacyWorkerVersion:l.version,versionsAligned:aligned,expected:{workerVersion:VERSION,adapterVersion:VERSION,databaseVersion:DB_VERSION,frontendVersion:FRONTEND_VERSION,legacyWorkerVersion:LEGACY_VERSION},time:new Date().toISOString()},aligned?200:503)}
async function check(req:Request){const h=await health(new Request(req.url,{headers:req.headers})),hd=await h.json();const dates=["2099-01-06","2099-01-10","2099-01-04","2099-01-05"];const cs=await Promise.all(dates.map(d=>getj(`${CORE}/api/calendar/evaluate?date=${d}`)));const checks=[{key:"versions_aligned",ok:hd.versionsAligned===true},{key:"cors_wildcard_absent",ok:hd.cors?.wildcard===false},{key:"database_version",ok:hd.databaseVersion===DB_VERSION},{key:"frontend_version",ok:hd.frontendVersion===FRONTEND_VERSION},{key:"legacy_health",ok:hd.legacyWorkerVersion===LEGACY_VERSION},{key:"weekly_open",ok:cs[0].data?.is_open===true&&cs[0].data?.source==="weekly_open"},{key:"weekly_closed",ok:cs[1].data?.is_open===false&&cs[1].data?.source==="weekly_closed"},{key:"special_open",ok:cs[2].data?.is_open===true&&cs[2].data?.source==="special_open_override"},{key:"temporary_closed",ok:cs[3].data?.is_open===false&&cs[3].data?.source==="temporary_closed_override"}];const bad=checks.filter(x=>!x.ok);return json(req,{ok:bad.length===0,service:"DPRO SHAROUSHI Safe Control Gateway",adapterVersion:VERSION,versionsAligned:hd.versionsAligned,summary:{total:checks.length,passed:checks.length-bad.length,failed:bad.length},checks,health:hd},bad.length?503:200)}
async function proxy(req:Request,path:string){const src=new URL(req.url),u=new URL(CORE+path);src.searchParams.forEach((v,k)=>u.searchParams.set(k,v));const hh=new Headers();["Content-Type","Authorization","X-Admin-Code","X-DPRO-Demo","X-Staff-Session","X-Line-ID-Token","X-Requested-With"].forEach(k=>{const v=req.headers.get(k);if(v)hh.set(k,v)});hh.set("Accept","application/json,text/plain,*/*");const body=["GET","HEAD"].includes(req.method)?undefined:await req.arrayBuffer();const r=await fetch(u.toString(),{method:req.method,headers:hh,body:body&&body.byteLength?body:undefined,redirect:"manual"}),out=await r.arrayBuffer(),rh=headers(req);rh.set("Content-Type",r.headers.get("Content-Type")||"application/json; charset=utf-8");return new Response(out,{status:r.status,headers:rh})}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS"){const o=origin(req);if(o&&!ALLOWED.includes(o))return new Response(null,{status:403,headers:new Headers({Vary:"Origin"})});return new Response(null,{status:204,headers:headers(req)})}if(!okOrigin(req))return fail(req,"ORIGIN_NOT_ALLOWED","Origin is not allowed",403);let p=new URL(req.url).pathname;p=p.replace(/^\/functions\/v1\/dpro-sharoushi-control-gateway-v2/,"").replace(/^\/dpro-sharoushi-control-gateway-v2/,"")||"/";if(p==="/api/health"&&req.method==="GET")return health(req);if(p==="/api/system-check"&&req.method==="GET")return check(req);if(p.startsWith("/api/"))return proxy(req,p);return json(req,{ok:true,service:"DPRO SHAROUSHI Safe Control Gateway",systemCode:SYSTEM_CODE,version:VERSION})});
